// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"go-reasonable-api/app/interfaces/repositories"
	"go-reasonable-api/db/sqlcgen"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthTokenRepository creates a new instance of MockAuthTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthTokenRepository {
	mock := &MockAuthTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthTokenRepository is an autogenerated mock type for the AuthTokenRepository type
type MockAuthTokenRepository struct {
	mock.Mock
}

type MockAuthTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthTokenRepository) EXPECT() *MockAuthTokenRepository_Expecter {
	return &MockAuthTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) Create(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) (*sqlcgen.AuthToken, error) {
	ret := _mock.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sqlcgen.AuthToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) (*sqlcgen.AuthToken, error)); ok {
		return returnFunc(ctx, userID, tokenHash, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) *sqlcgen.AuthToken); ok {
		r0 = returnFunc(ctx, userID, tokenHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockAuthTokenRepository_Expecter) Create(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockAuthTokenRepository_Create_Call {
	return &MockAuthTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, tokenHash, expiresAt)}
}

func (_c *MockAuthTokenRepository_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time)) *MockAuthTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_Create_Call) Return(authToken *sqlcgen.AuthToken, err error) *MockAuthTokenRepository_Create_Call {
	_c.Call.Return(authToken, err)
	return _c
}

func (_c *MockAuthTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) (*sqlcgen.AuthToken, error)) *MockAuthTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredOrRevoked provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) DeleteExpiredOrRevoked(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredOrRevoked")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenRepository_DeleteExpiredOrRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredOrRevoked'
type MockAuthTokenRepository_DeleteExpiredOrRevoked_Call struct {
	*mock.Call
}

// DeleteExpiredOrRevoked is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthTokenRepository_Expecter) DeleteExpiredOrRevoked(ctx interface{}) *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call {
	return &MockAuthTokenRepository_DeleteExpiredOrRevoked_Call{Call: _e.mock.On("DeleteExpiredOrRevoked", ctx)}
}

func (_c *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call) Run(run func(ctx context.Context)) *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call) Return(n int64, err error) *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockAuthTokenRepository_DeleteExpiredOrRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) GetByHash(ctx context.Context, tokenHash string) (*sqlcgen.AuthToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *sqlcgen.AuthToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sqlcgen.AuthToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sqlcgen.AuthToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockAuthTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAuthTokenRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockAuthTokenRepository_GetByHash_Call {
	return &MockAuthTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockAuthTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAuthTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_GetByHash_Call) Return(authToken *sqlcgen.AuthToken, err error) *MockAuthTokenRepository_GetByHash_Call {
	_c.Call.Return(authToken, err)
	return _c
}

func (_c *MockAuthTokenRepository_GetByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*sqlcgen.AuthToken, error)) *MockAuthTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockAuthTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthTokenRepository_Expecter) Revoke(ctx interface{}, id interface{}) *MockAuthTokenRepository_Revoke_Call {
	return &MockAuthTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockAuthTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_Revoke_Call) Return(err error) *MockAuthTokenRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthTokenRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockAuthTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthTokenRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockAuthTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockAuthTokenRepository_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *MockAuthTokenRepository_RevokeAllForUser_Call {
	return &MockAuthTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *MockAuthTokenRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockAuthTokenRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_RevokeAllForUser_Call) Return(err error) *MockAuthTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockAuthTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByHash provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) RevokeByHash(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthTokenRepository_RevokeByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByHash'
type MockAuthTokenRepository_RevokeByHash_Call struct {
	*mock.Call
}

// RevokeByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockAuthTokenRepository_Expecter) RevokeByHash(ctx interface{}, tokenHash interface{}) *MockAuthTokenRepository_RevokeByHash_Call {
	return &MockAuthTokenRepository_RevokeByHash_Call{Call: _e.mock.On("RevokeByHash", ctx, tokenHash)}
}

func (_c *MockAuthTokenRepository_RevokeByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockAuthTokenRepository_RevokeByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_RevokeByHash_Call) Return(err error) *MockAuthTokenRepository_RevokeByHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthTokenRepository_RevokeByHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *MockAuthTokenRepository_RevokeByHash_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockAuthTokenRepository
func (_mock *MockAuthTokenRepository) WithTx(tx *sql.Tx) repositories.AuthTokenRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.AuthTokenRepository
	if returnFunc, ok := ret.Get(0).(func(*sql.Tx) repositories.AuthTokenRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.AuthTokenRepository)
		}
	}
	return r0
}

// MockAuthTokenRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockAuthTokenRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockAuthTokenRepository_Expecter) WithTx(tx interface{}) *MockAuthTokenRepository_WithTx_Call {
	return &MockAuthTokenRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockAuthTokenRepository_WithTx_Call) Run(run func(tx *sql.Tx)) *MockAuthTokenRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sql.Tx
		if args[0] != nil {
			arg0 = args[0].(*sql.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthTokenRepository_WithTx_Call) Return(authTokenRepository repositories.AuthTokenRepository) *MockAuthTokenRepository_WithTx_Call {
	_c.Call.Return(authTokenRepository)
	return _c
}

func (_c *MockAuthTokenRepository_WithTx_Call) RunAndReturn(run func(tx *sql.Tx) repositories.AuthTokenRepository) *MockAuthTokenRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
