// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"go-reasonable-api/app/interfaces/repositories"
	"go-reasonable-api/db/sqlcgen"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailVerificationRepository creates a new instance of MockEmailVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailVerificationRepository is an autogenerated mock type for the EmailVerificationRepository type
type MockEmailVerificationRepository struct {
	mock.Mock
}

type MockEmailVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepository_Expecter {
	return &MockEmailVerificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) Create(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) (*sqlcgen.EmailVerification, error) {
	ret := _mock.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sqlcgen.EmailVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) (*sqlcgen.EmailVerification, error)); ok {
		return returnFunc(ctx, userID, tokenHash, expiresAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) *sqlcgen.EmailVerification); ok {
		r0 = returnFunc(ctx, userID, tokenHash, expiresAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.EmailVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, tokenHash, expiresAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailVerificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenHash string
//   - expiresAt time.Time
func (_e *MockEmailVerificationRepository_Expecter) Create(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *MockEmailVerificationRepository_Create_Call {
	return &MockEmailVerificationRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, tokenHash, expiresAt)}
}

func (_c *MockEmailVerificationRepository_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time)) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) Return(emailVerification *sqlcgen.EmailVerification, err error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(emailVerification, err)
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) (*sqlcgen.EmailVerification, error)) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredOrUsed provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) DeleteExpiredOrUsed(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredOrUsed")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationRepository_DeleteExpiredOrUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredOrUsed'
type MockEmailVerificationRepository_DeleteExpiredOrUsed_Call struct {
	*mock.Call
}

// DeleteExpiredOrUsed is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEmailVerificationRepository_Expecter) DeleteExpiredOrUsed(ctx interface{}) *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call {
	return &MockEmailVerificationRepository_DeleteExpiredOrUsed_Call{Call: _e.mock.On("DeleteExpiredOrUsed", ctx)}
}

func (_c *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call) Run(run func(ctx context.Context)) *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call) Return(n int64, err error) *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockEmailVerificationRepository_DeleteExpiredOrUsed_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) GetByTokenHash(ctx context.Context, tokenHash string) (*sqlcgen.EmailVerification, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *sqlcgen.EmailVerification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sqlcgen.EmailVerification, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sqlcgen.EmailVerification); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.EmailVerification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockEmailVerificationRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockEmailVerificationRepository_Expecter) GetByTokenHash(ctx interface{}, tokenHash interface{}) *MockEmailVerificationRepository_GetByTokenHash_Call {
	return &MockEmailVerificationRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash", ctx, tokenHash)}
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) Return(emailVerification *sqlcgen.EmailVerification, err error) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Return(emailVerification, err)
	return _c
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*sqlcgen.EmailVerification, error)) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateAllForUser provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) InvalidateAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAllForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_InvalidateAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateAllForUser'
type MockEmailVerificationRepository_InvalidateAllForUser_Call struct {
	*mock.Call
}

// InvalidateAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEmailVerificationRepository_Expecter) InvalidateAllForUser(ctx interface{}, userID interface{}) *MockEmailVerificationRepository_InvalidateAllForUser_Call {
	return &MockEmailVerificationRepository_InvalidateAllForUser_Call{Call: _e.mock.On("InvalidateAllForUser", ctx, userID)}
}

func (_c *MockEmailVerificationRepository_InvalidateAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEmailVerificationRepository_InvalidateAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_InvalidateAllForUser_Call) Return(err error) *MockEmailVerificationRepository_InvalidateAllForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_InvalidateAllForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockEmailVerificationRepository_InvalidateAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) MarkUsed(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockEmailVerificationRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockEmailVerificationRepository_Expecter) MarkUsed(ctx interface{}, id interface{}) *MockEmailVerificationRepository_MarkUsed_Call {
	return &MockEmailVerificationRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) Return(err error) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) WithTx(tx *sql.Tx) repositories.EmailVerificationRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.EmailVerificationRepository
	if returnFunc, ok := ret.Get(0).(func(*sql.Tx) repositories.EmailVerificationRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.EmailVerificationRepository)
		}
	}
	return r0
}

// MockEmailVerificationRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockEmailVerificationRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockEmailVerificationRepository_Expecter) WithTx(tx interface{}) *MockEmailVerificationRepository_WithTx_Call {
	return &MockEmailVerificationRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockEmailVerificationRepository_WithTx_Call) Run(run func(tx *sql.Tx)) *MockEmailVerificationRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sql.Tx
		if args[0] != nil {
			arg0 = args[0].(*sql.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_WithTx_Call) Return(emailVerificationRepository repositories.EmailVerificationRepository) *MockEmailVerificationRepository_WithTx_Call {
	_c.Call.Return(emailVerificationRepository)
	return _c
}

func (_c *MockEmailVerificationRepository_WithTx_Call) RunAndReturn(run func(tx *sql.Tx) repositories.EmailVerificationRepository) *MockEmailVerificationRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
