// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"
	"go-reasonable-api/app/interfaces/repositories"
	"go-reasonable-api/db/sqlcgen"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CancelDeletion provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CancelDeletion(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelDeletion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_CancelDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelDeletion'
type MockUserRepository_CancelDeletion_Call struct {
	*mock.Call
}

// CancelDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) CancelDeletion(ctx interface{}, userID interface{}) *MockUserRepository_CancelDeletion_Call {
	return &MockUserRepository_CancelDeletion_Call{Call: _e.mock.On("CancelDeletion", ctx, userID)}
}

func (_c *MockUserRepository_CancelDeletion_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_CancelDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_CancelDeletion_Call) Return(err error) *MockUserRepository_CancelDeletion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_CancelDeletion_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockUserRepository_CancelDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, name string, email string, passwordHash string) (*sqlcgen.User, error) {
	ret := _mock.Called(ctx, name, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sqlcgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*sqlcgen.User, error)); ok {
		return returnFunc(ctx, name, email, passwordHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *sqlcgen.User); ok {
		r0 = returnFunc(ctx, name, email, passwordHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - passwordHash string
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, name interface{}, email interface{}, passwordHash interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, email, passwordHash)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, name string, email string, passwordHash string)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(user *sqlcgen.User, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, name string, email string, passwordHash string) (*sqlcgen.User, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteScheduledUsers provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteScheduledUsers(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScheduledUsers")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_DeleteScheduledUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteScheduledUsers'
type MockUserRepository_DeleteScheduledUsers_Call struct {
	*mock.Call
}

// DeleteScheduledUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) DeleteScheduledUsers(ctx interface{}) *MockUserRepository_DeleteScheduledUsers_Call {
	return &MockUserRepository_DeleteScheduledUsers_Call{Call: _e.mock.On("DeleteScheduledUsers", ctx)}
}

func (_c *MockUserRepository_DeleteScheduledUsers_Call) Run(run func(ctx context.Context)) *MockUserRepository_DeleteScheduledUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteScheduledUsers_Call) Return(n int64, err error) *MockUserRepository_DeleteScheduledUsers_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepository_DeleteScheduledUsers_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockUserRepository_DeleteScheduledUsers_Call {
	_c.Call.Return(run)
	return _c
}

// EmailExists provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) EmailExists(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for EmailExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_EmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailExists'
type MockUserRepository_EmailExists_Call struct {
	*mock.Call
}

// EmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) EmailExists(ctx interface{}, email interface{}) *MockUserRepository_EmailExists_Call {
	return &MockUserRepository_EmailExists_Call{Call: _e.mock.On("EmailExists", ctx, email)}
}

func (_c *MockUserRepository_EmailExists_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_EmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_EmailExists_Call) Return(b bool, err error) *MockUserRepository_EmailExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_EmailExists_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockUserRepository_EmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByEmail(ctx context.Context, email string) (*sqlcgen.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *sqlcgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sqlcgen.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sqlcgen.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user *sqlcgen.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*sqlcgen.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*sqlcgen.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *sqlcgen.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*sqlcgen.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *sqlcgen.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(user *sqlcgen.User, err error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*sqlcgen.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEmailVerified provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) MarkEmailVerified(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerified")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_MarkEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEmailVerified'
type MockUserRepository_MarkEmailVerified_Call struct {
	*mock.Call
}

// MarkEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserRepository_Expecter) MarkEmailVerified(ctx interface{}, userID interface{}) *MockUserRepository_MarkEmailVerified_Call {
	return &MockUserRepository_MarkEmailVerified_Call{Call: _e.mock.On("MarkEmailVerified", ctx, userID)}
}

func (_c *MockUserRepository_MarkEmailVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserRepository_MarkEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_MarkEmailVerified_Call) Return(err error) *MockUserRepository_MarkEmailVerified_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_MarkEmailVerified_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockUserRepository_MarkEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// ScheduleDeletion provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ScheduleDeletion(ctx context.Context, userID uuid.UUID, scheduledAt time.Time) error {
	ret := _mock.Called(ctx, userID, scheduledAt)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleDeletion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, scheduledAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_ScheduleDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleDeletion'
type MockUserRepository_ScheduleDeletion_Call struct {
	*mock.Call
}

// ScheduleDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - scheduledAt time.Time
func (_e *MockUserRepository_Expecter) ScheduleDeletion(ctx interface{}, userID interface{}, scheduledAt interface{}) *MockUserRepository_ScheduleDeletion_Call {
	return &MockUserRepository_ScheduleDeletion_Call{Call: _e.mock.On("ScheduleDeletion", ctx, userID, scheduledAt)}
}

func (_c *MockUserRepository_ScheduleDeletion_Call) Run(run func(ctx context.Context, userID uuid.UUID, scheduledAt time.Time)) *MockUserRepository_ScheduleDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_ScheduleDeletion_Call) Return(err error) *MockUserRepository_ScheduleDeletion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_ScheduleDeletion_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, scheduledAt time.Time) error) *MockUserRepository_ScheduleDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, passwordHash string) error {
	ret := _mock.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - passwordHash string
func (_e *MockUserRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwordHash interface{}) *MockUserRepository_UpdatePassword_Call {
	return &MockUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwordHash)}
}

func (_c *MockUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, passwordHash string)) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdatePassword_Call) Return(err error) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, passwordHash string) error) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) WithTx(tx *sql.Tx) repositories.UserRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repositories.UserRepository
	if returnFunc, ok := ret.Get(0).(func(*sql.Tx) repositories.UserRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.UserRepository)
		}
	}
	return r0
}

// MockUserRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockUserRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockUserRepository_Expecter) WithTx(tx interface{}) *MockUserRepository_WithTx_Call {
	return &MockUserRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockUserRepository_WithTx_Call) Run(run func(tx *sql.Tx)) *MockUserRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sql.Tx
		if args[0] != nil {
			arg0 = args[0].(*sql.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_WithTx_Call) Return(userRepository repositories.UserRepository) *MockUserRepository_WithTx_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockUserRepository_WithTx_Call) RunAndReturn(run func(tx *sql.Tx) repositories.UserRepository) *MockUserRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
