// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailVerificationService creates a new instance of MockEmailVerificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationService {
	mock := &MockEmailVerificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailVerificationService is an autogenerated mock type for the EmailVerificationService type
type MockEmailVerificationService struct {
	mock.Mock
}

type MockEmailVerificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationService) EXPECT() *MockEmailVerificationService_Expecter {
	return &MockEmailVerificationService_Expecter{mock: &_m.Mock}
}

// Resend provides a mock function for the type MockEmailVerificationService
func (_mock *MockEmailVerificationService) Resend(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Resend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationService_Resend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resend'
type MockEmailVerificationService_Resend_Call struct {
	*mock.Call
}

// Resend is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockEmailVerificationService_Expecter) Resend(ctx interface{}, email interface{}) *MockEmailVerificationService_Resend_Call {
	return &MockEmailVerificationService_Resend_Call{Call: _e.mock.On("Resend", ctx, email)}
}

func (_c *MockEmailVerificationService_Resend_Call) Run(run func(ctx context.Context, email string)) *MockEmailVerificationService_Resend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationService_Resend_Call) Return(err error) *MockEmailVerificationService_Resend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationService_Resend_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockEmailVerificationService_Resend_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockEmailVerificationService
func (_mock *MockEmailVerificationService) Send(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockEmailVerificationService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEmailVerificationService_Expecter) Send(ctx interface{}, userID interface{}) *MockEmailVerificationService_Send_Call {
	return &MockEmailVerificationService_Send_Call{Call: _e.mock.On("Send", ctx, userID)}
}

func (_c *MockEmailVerificationService_Send_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEmailVerificationService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationService_Send_Call) Return(err error) *MockEmailVerificationService_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationService_Send_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockEmailVerificationService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockEmailVerificationService
func (_mock *MockEmailVerificationService) Verify(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationService_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockEmailVerificationService_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockEmailVerificationService_Expecter) Verify(ctx interface{}, token interface{}) *MockEmailVerificationService_Verify_Call {
	return &MockEmailVerificationService_Verify_Call{Call: _e.mock.On("Verify", ctx, token)}
}

func (_c *MockEmailVerificationService_Verify_Call) Run(run func(ctx context.Context, token string)) *MockEmailVerificationService_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailVerificationService_Verify_Call) Return(err error) *MockEmailVerificationService_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationService_Verify_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockEmailVerificationService_Verify_Call {
	_c.Call.Return(run)
	return _c
}
