// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordResetService creates a new instance of MockPasswordResetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetService {
	mock := &MockPasswordResetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordResetService is an autogenerated mock type for the PasswordResetService type
type MockPasswordResetService struct {
	mock.Mock
}

type MockPasswordResetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetService) EXPECT() *MockPasswordResetService_Expecter {
	return &MockPasswordResetService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPasswordResetService
func (_mock *MockPasswordResetService) Create(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordResetService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasswordResetService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockPasswordResetService_Expecter) Create(ctx interface{}, email interface{}) *MockPasswordResetService_Create_Call {
	return &MockPasswordResetService_Create_Call{Call: _e.mock.On("Create", ctx, email)}
}

func (_c *MockPasswordResetService_Create_Call) Run(run func(ctx context.Context, email string)) *MockPasswordResetService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordResetService_Create_Call) Return(err error) *MockPasswordResetService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordResetService_Create_Call) RunAndReturn(run func(ctx context.Context, email string) error) *MockPasswordResetService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockPasswordResetService
func (_mock *MockPasswordResetService) Execute(ctx context.Context, token string, newPassword string) error {
	ret := _mock.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, token, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordResetService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPasswordResetService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *MockPasswordResetService_Expecter) Execute(ctx interface{}, token interface{}, newPassword interface{}) *MockPasswordResetService_Execute_Call {
	return &MockPasswordResetService_Execute_Call{Call: _e.mock.On("Execute", ctx, token, newPassword)}
}

func (_c *MockPasswordResetService_Execute_Call) Run(run func(ctx context.Context, token string, newPassword string)) *MockPasswordResetService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPasswordResetService_Execute_Call) Return(err error) *MockPasswordResetService_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordResetService_Execute_Call) RunAndReturn(run func(ctx context.Context, token string, newPassword string) error) *MockPasswordResetService_Execute_Call {
	_c.Call.Return(run)
	return _c
}
