// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-reasonable-api/db/sqlcgen"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

type MockSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionService) EXPECT() *MockSessionService_Expecter {
	return &MockSessionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionService
func (_mock *MockSessionService) Create(ctx context.Context, email string, password string) (*sqlcgen.User, string, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sqlcgen.User
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*sqlcgen.User, string, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *sqlcgen.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSessionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockSessionService_Expecter) Create(ctx interface{}, email interface{}, password interface{}) *MockSessionService_Create_Call {
	return &MockSessionService_Create_Call{Call: _e.mock.On("Create", ctx, email, password)}
}

func (_c *MockSessionService_Create_Call) Run(run func(ctx context.Context, email string, password string)) *MockSessionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionService_Create_Call) Return(user *sqlcgen.User, s string, err error) *MockSessionService_Create_Call {
	_c.Call.Return(user, s, err)
	return _c
}

func (_c *MockSessionService_Create_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*sqlcgen.User, string, error)) *MockSessionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateForUser provides a mock function for the type MockSessionService
func (_mock *MockSessionService) CreateForUser(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateForUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_CreateForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateForUser'
type MockSessionService_CreateForUser_Call struct {
	*mock.Call
}

// CreateForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionService_Expecter) CreateForUser(ctx interface{}, userID interface{}) *MockSessionService_CreateForUser_Call {
	return &MockSessionService_CreateForUser_Call{Call: _e.mock.On("CreateForUser", ctx, userID)}
}

func (_c *MockSessionService_CreateForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionService_CreateForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_CreateForUser_Call) Return(s string, err error) *MockSessionService_CreateForUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSessionService_CreateForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockSessionService_CreateForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionService
func (_mock *MockSessionService) Delete(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionService_Expecter) Delete(ctx interface{}, token interface{}) *MockSessionService_Delete_Call {
	return &MockSessionService_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockSessionService_Delete_Call) Run(run func(ctx context.Context, token string)) *MockSessionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_Delete_Call) Return(err error) *MockSessionService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionService_Delete_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockSessionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockSessionService
func (_mock *MockSessionService) ValidateToken(ctx context.Context, token string) (*sqlcgen.AuthToken, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *sqlcgen.AuthToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sqlcgen.AuthToken, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sqlcgen.AuthToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlcgen.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionService_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockSessionService_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionService_Expecter) ValidateToken(ctx interface{}, token interface{}) *MockSessionService_ValidateToken_Call {
	return &MockSessionService_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *MockSessionService_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *MockSessionService_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionService_ValidateToken_Call) Return(authToken *sqlcgen.AuthToken, err error) *MockSessionService_ValidateToken_Call {
	_c.Call.Return(authToken, err)
	return _c
}

func (_c *MockSessionService_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*sqlcgen.AuthToken, error)) *MockSessionService_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
