// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAuthToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOrRevokedAuthTokens = `-- name: DeleteExpiredOrRevokedAuthTokens :execrows
DELETE FROM auth_tokens WHERE expires_at < $1 OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOrRevokedAuthTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOrRevokedAuthTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at FROM auth_tokens WHERE token_hash = $1
`

func (q *Queries) GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getAuthTokenByHash, tokenHash)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllAuthTokensForUser = `-- name: RevokeAllAuthTokensForUser :exec
UPDATE auth_tokens SET revoked_at = $1 WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeAllAuthTokensForUserParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	UserID    uuid.UUID  `json:"user_id"`
}

func (q *Queries) RevokeAllAuthTokensForUser(ctx context.Context, arg RevokeAllAuthTokensForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllAuthTokensForUser, arg.RevokedAt, arg.UserID)
	return err
}

const revokeAuthToken = `-- name: RevokeAuthToken :exec
UPDATE auth_tokens SET revoked_at = $1 WHERE id = $2
`

type RevokeAuthTokenParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) RevokeAuthToken(ctx context.Context, arg RevokeAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeAuthToken, arg.RevokedAt, arg.ID)
	return err
}

const revokeAuthTokenByHash = `-- name: RevokeAuthTokenByHash :exec
UPDATE auth_tokens SET revoked_at = $1 WHERE token_hash = $2
`

type RevokeAuthTokenByHashParams struct {
	RevokedAt *time.Time `json:"revoked_at"`
	TokenHash string     `json:"token_hash"`
}

func (q *Queries) RevokeAuthTokenByHash(ctx context.Context, arg RevokeAuthTokenByHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeAuthTokenByHash, arg.RevokedAt, arg.TokenHash)
	return err
}
