// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verifications (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateEmailVerificationParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerification,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOrUsedEmailVerifications = `-- name: DeleteExpiredOrUsedEmailVerifications :execrows
DELETE FROM email_verifications WHERE expires_at < $1 OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOrUsedEmailVerifications(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOrUsedEmailVerifications, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEmailVerificationByTokenHash = `-- name: GetEmailVerificationByTokenHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM email_verifications WHERE token_hash = $1
`

func (q *Queries) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerification, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerificationByTokenHash, tokenHash)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateAllEmailVerificationsForUser = `-- name: InvalidateAllEmailVerificationsForUser :exec
UPDATE email_verifications SET used_at = $1 WHERE user_id = $2 AND used_at IS NULL
`

type InvalidateAllEmailVerificationsForUserParams struct {
	UsedAt *time.Time `json:"used_at"`
	UserID uuid.UUID  `json:"user_id"`
}

func (q *Queries) InvalidateAllEmailVerificationsForUser(ctx context.Context, arg InvalidateAllEmailVerificationsForUserParams) error {
	_, err := q.db.ExecContext(ctx, invalidateAllEmailVerificationsForUser, arg.UsedAt, arg.UserID)
	return err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications SET used_at = $1 WHERE id = $2
`

type MarkEmailVerificationUsedParams struct {
	UsedAt *time.Time `json:"used_at"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, arg MarkEmailVerificationUsedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailVerificationUsed, arg.UsedAt, arg.ID)
	return err
}
