// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePasswordResetParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOrUsedPasswordResets = `-- name: DeleteExpiredOrUsedPasswordResets :execrows
DELETE FROM password_resets WHERE expires_at < $1 OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredOrUsedPasswordResets(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredOrUsedPasswordResets, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_resets WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByTokenHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateAllPasswordResetsForUser = `-- name: InvalidateAllPasswordResetsForUser :exec
UPDATE password_resets SET used_at = $1 WHERE user_id = $2 AND used_at IS NULL
`

type InvalidateAllPasswordResetsForUserParams struct {
	UsedAt *time.Time `json:"used_at"`
	UserID uuid.UUID  `json:"user_id"`
}

func (q *Queries) InvalidateAllPasswordResetsForUser(ctx context.Context, arg InvalidateAllPasswordResetsForUserParams) error {
	_, err := q.db.ExecContext(ctx, invalidateAllPasswordResetsForUser, arg.UsedAt, arg.UserID)
	return err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets SET used_at = $1 WHERE id = $2
`

type MarkPasswordResetUsedParams struct {
	UsedAt *time.Time `json:"used_at"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, arg MarkPasswordResetUsedParams) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetUsed, arg.UsedAt, arg.ID)
	return err
}
