// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CancelUserDeletion(ctx context.Context, arg CancelUserDeletionParams) error
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredOrRevokedAuthTokens(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteExpiredOrUsedEmailVerifications(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteExpiredOrUsedPasswordResets(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteScheduledUsers(ctx context.Context, deletionScheduledAt *time.Time) (int64, error)
	EmailExists(ctx context.Context, email string) (bool, error)
	GetAuthTokenByHash(ctx context.Context, tokenHash string) (AuthToken, error)
	GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerification, error)
	GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InvalidateAllEmailVerificationsForUser(ctx context.Context, arg InvalidateAllEmailVerificationsForUserParams) error
	InvalidateAllPasswordResetsForUser(ctx context.Context, arg InvalidateAllPasswordResetsForUserParams) error
	MarkEmailVerificationUsed(ctx context.Context, arg MarkEmailVerificationUsedParams) error
	MarkPasswordResetUsed(ctx context.Context, arg MarkPasswordResetUsedParams) error
	MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) error
	RevokeAllAuthTokensForUser(ctx context.Context, arg RevokeAllAuthTokensForUserParams) error
	RevokeAuthToken(ctx context.Context, arg RevokeAuthTokenParams) error
	RevokeAuthTokenByHash(ctx context.Context, arg RevokeAuthTokenByHashParams) error
	ScheduleUserDeletion(ctx context.Context, arg ScheduleUserDeletionParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
