// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cancelUserDeletion = `-- name: CancelUserDeletion :exec
UPDATE users SET deletion_scheduled_at = NULL, updated_at = $1 WHERE id = $2
`

type CancelUserDeletionParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) CancelUserDeletion(ctx context.Context, arg CancelUserDeletionParams) error {
	_, err := q.db.ExecContext(ctx, cancelUserDeletion, arg.UpdatedAt, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, password_hash, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, password_hash, email_verified_at, deletion_scheduled_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduledUsers = `-- name: DeleteScheduledUsers :execrows
DELETE FROM users WHERE deletion_scheduled_at IS NOT NULL AND deletion_scheduled_at <= $1
`

func (q *Queries) DeleteScheduledUsers(ctx context.Context, deletionScheduledAt *time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteScheduledUsers, deletionScheduledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, email_verified_at, deletion_scheduled_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, email_verified_at, deletion_scheduled_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DeletionScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users SET email_verified_at = $1, updated_at = $2 WHERE id = $3
`

type MarkUserEmailVerifiedParams struct {
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	ID              uuid.UUID  `json:"id"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, markUserEmailVerified, arg.EmailVerifiedAt, arg.UpdatedAt, arg.ID)
	return err
}

const scheduleUserDeletion = `-- name: ScheduleUserDeletion :exec
UPDATE users SET deletion_scheduled_at = $1, updated_at = $2 WHERE id = $3
`

type ScheduleUserDeletionParams struct {
	DeletionScheduledAt *time.Time `json:"deletion_scheduled_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	ID                  uuid.UUID  `json:"id"`
}

func (q *Queries) ScheduleUserDeletion(ctx context.Context, arg ScheduleUserDeletionParams) error {
	_, err := q.db.ExecContext(ctx, scheduleUserDeletion, arg.DeletionScheduledAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = $2 WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}
