// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hibiken/asynq"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskClient creates a new instance of MockTaskClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskClient {
	mock := &MockTaskClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskClient is an autogenerated mock type for the TaskClient type
type MockTaskClient struct {
	mock.Mock
}

type MockTaskClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskClient) EXPECT() *MockTaskClient_Expecter {
	return &MockTaskClient_Expecter{mock: &_m.Mock}
}

// EnqueueCtx provides a mock function for the type MockTaskClient
func (_mock *MockTaskClient) EnqueueCtx(ctx context.Context, taskType string, payload any, opts ...asynq.Option) {
	// asynq.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, taskType, payload)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockTaskClient_EnqueueCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueCtx'
type MockTaskClient_EnqueueCtx_Call struct {
	*mock.Call
}

// EnqueueCtx is a helper method to define mock.On call
//   - ctx context.Context
//   - taskType string
//   - payload any
//   - opts ...asynq.Option
func (_e *MockTaskClient_Expecter) EnqueueCtx(ctx interface{}, taskType interface{}, payload interface{}, opts ...interface{}) *MockTaskClient_EnqueueCtx_Call {
	return &MockTaskClient_EnqueueCtx_Call{Call: _e.mock.On("EnqueueCtx",
		append([]interface{}{ctx, taskType, payload}, opts...)...)}
}

func (_c *MockTaskClient_EnqueueCtx_Call) Run(run func(ctx context.Context, taskType string, payload any, opts ...asynq.Option)) *MockTaskClient_EnqueueCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []asynq.Option
		variadicArgs := make([]asynq.Option, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(asynq.Option)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockTaskClient_EnqueueCtx_Call) Return() *MockTaskClient_EnqueueCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskClient_EnqueueCtx_Call) RunAndReturn(run func(ctx context.Context, taskType string, payload any, opts ...asynq.Option)) *MockTaskClient_EnqueueCtx_Call {
	_c.Run(run)
	return _c
}
