// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/hibiken/asynq"
	"go-reasonable-api/api/handlers"
	repositories2 "go-reasonable-api/app/interfaces/repositories"
	services2 "go-reasonable-api/app/interfaces/services"
	"go-reasonable-api/app/repositories"
	"go-reasonable-api/app/services"
	"go-reasonable-api/support/config"
	"go-reasonable-api/support/http"
	"go-reasonable-api/support/wire/providers"
	"go-reasonable-api/support/worker"
)

// Injectors from wire.go:

// InitializeRouter creates the API router with all dependencies.
// The cleanup function closes database connections and should be
// deferred in main.
func InitializeRouter() (*http.Router, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	logger := providers.ProvideLogger(configConfig)
	db, cleanup, err := providers.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	txManager := providers.ProvideTxManager(db)
	userRepository := repositories.NewUserRepository(db)
	authTokenRepository := repositories.NewAuthTokenRepository(db)
	client, cleanup2, err := providers.ProvideAsynqClient(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	taskClient := providers.ProvideTaskClient(client)
	userService := services.NewUserService(configConfig, txManager, userRepository, authTokenRepository, taskClient)
	sessionService := services.NewSessionService(configConfig, userRepository, authTokenRepository)
	userHandler := handlers.NewUserHandler(userService, sessionService)
	sessionHandler := handlers.NewSessionHandler(sessionService)
	passwordResetRepository := repositories.NewPasswordResetRepository(db)
	passwordResetService := services.NewPasswordResetService(configConfig, userRepository, passwordResetRepository, authTokenRepository, txManager, taskClient)
	passwordResetHandler := handlers.NewPasswordResetHandler(passwordResetService)
	emailVerificationRepository := repositories.NewEmailVerificationRepository(db)
	emailVerificationService := services.NewEmailVerificationService(configConfig, userRepository, emailVerificationRepository, txManager, taskClient)
	emailVerificationHandler := handlers.NewEmailVerificationHandler(emailVerificationService)
	healthHandler := handlers.NewHealthHandler(db, client)
	router := http.NewRouter(configConfig, logger, userHandler, sessionHandler, passwordResetHandler, emailVerificationHandler, healthHandler, sessionService)
	return router, func() {
		cleanup2()
		cleanup()
	}, nil
}

// InitializeWorker creates the background worker with all dependencies.
// The cleanup function closes database connections and should be
// deferred in main.
func InitializeWorker() (*worker.Worker, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	logger := providers.ProvideLogger(configConfig)
	server := providers.ProvideAsynqServer(configConfig, logger)
	emailSender := providers.ProvideEmailSender(configConfig)
	emailTask, err := providers.ProvideEmailTask(logger, emailSender)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := providers.ProvideDB(configConfig)
	if err != nil {
		return nil, nil, err
	}
	authTokenRepository := repositories.NewAuthTokenRepository(db)
	passwordResetRepository := repositories.NewPasswordResetRepository(db)
	emailVerificationRepository := repositories.NewEmailVerificationRepository(db)
	userRepository := repositories.NewUserRepository(db)
	cleanupTask := providers.ProvideCleanupTask(logger, authTokenRepository, passwordResetRepository, emailVerificationRepository, userRepository)
	registry := providers.ProvideTaskRegistry(emailTask, cleanupTask)
	serveMux := providers.ProvideServeMux(registry)
	scheduler := providers.ProvideScheduler(configConfig)
	workerWorker := providers.ProvideWorker(server, serveMux, scheduler, registry, logger)
	return workerWorker, func() {
		cleanup()
	}, nil
}

// wire.go:

// BaseProviderSet contains providers shared between API and Worker
var BaseProviderSet = wire.NewSet(config.Load, providers.ProvideLogger, providers.ProvideEmailSender)

// RepositoryProviderSet contains all repository providers
var RepositoryProviderSet = wire.NewSet(repositories.NewUserRepository, wire.Bind(new(repositories2.UserRepository), new(*repositories.UserRepository)), repositories.NewAuthTokenRepository, wire.Bind(new(repositories2.AuthTokenRepository), new(*repositories.AuthTokenRepository)), repositories.NewPasswordResetRepository, wire.Bind(new(repositories2.PasswordResetRepository), new(*repositories.PasswordResetRepository)), repositories.NewEmailVerificationRepository, wire.Bind(new(repositories2.EmailVerificationRepository), new(*repositories.EmailVerificationRepository)))

// ServiceProviderSet contains all service providers
var ServiceProviderSet = wire.NewSet(services.NewUserService, wire.Bind(new(services2.UserService), new(*services.UserService)), services.NewSessionService, wire.Bind(new(services2.SessionService), new(*services.SessionService)), services.NewPasswordResetService, wire.Bind(new(services2.PasswordResetService), new(*services.PasswordResetService)), services.NewEmailVerificationService, wire.Bind(new(services2.EmailVerificationService), new(*services.EmailVerificationService)))

// HandlerProviderSet contains all handler providers
var HandlerProviderSet = wire.NewSet(handlers.NewUserHandler, handlers.NewSessionHandler, handlers.NewPasswordResetHandler, handlers.NewEmailVerificationHandler, handlers.NewHealthHandler)

// APIProviderSet contains providers specific to the API
var APIProviderSet = wire.NewSet(
	BaseProviderSet, providers.ProvideDB, providers.ProvideTxManager, providers.ProvideAsynqClient, wire.Bind(new(handlers.RedisPinger), new(*asynq.Client)), providers.ProvideTaskClient, RepositoryProviderSet,
	ServiceProviderSet,
	HandlerProviderSet, http.NewRouter,
)

// WorkerProviderSet contains providers specific to the Worker
var WorkerProviderSet = wire.NewSet(
	BaseProviderSet, providers.ProvideDB, RepositoryProviderSet, providers.ProvideAsynqServer, providers.ProvideScheduler, providers.ProvideEmailTask, providers.ProvideCleanupTask, providers.ProvideTaskRegistry, providers.ProvideServeMux, providers.ProvideWorker,
)
